# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Principles of MRI
author: Peder Larson
email: peder.larson@ucsf.edu
logo: images/HPBrain-Anime.png
copyright: "2023"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: "auto"  # default is "auto", or "off"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: MRI-education-book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/larsonlab/MRI-education-resources  # Online location of your book
  path_to_book: Notebooks  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  extra_navbar              : >-  # Will be displayed underneath the left navbar.
    <a href="https://larsonlab.github.io">Larson Advanced Imaging Research Group</a>
    Powered by <a href="https://jupyterbook.org">Jupyter Book</a> 
  extra_footer              : Citation - DOI <a href="https://doi.org/10.5281/zenodo.5547020">10.5281/zenodo.5547020</a> # <a href="https://doi.org/10.5281/zenodo.5547020"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.5547020.svg" alt="DOI"></a>  # Will be displayed underneath the footer.
  google_analytics_id       : "UA-51903906-1"  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar


description: >- # this means to ignore newlines until "baseurl:"
  This is an introduction to the principles of magnetic resonance imaging (MRI)
  
# # the name of your GitHub Repo. 
# # If there is no subpath for your site, use an empty string ""  
# baseurl: "/MRI-education-resouces"

# # the base hostname & protocol for your site. 
# url: "https://LarsonLab.github.io/"

# #######################
# # Jupyter Book settings
# #######################

# # Main page settings
# # Optional: you can replace with <https://github.com/my-first-jupyter-book/my-book-site> your repo URL
# footer_text               : View source repository at <a href="https://github.com/my-first-jupyter-book/my-book-site"></a> #@@@ CHANGE THIS - 7 @@@#

# # Sidebar settings
# show_sidebar              : true  # Show the sidebar. Only set to false if your only wish to host a single page.
# collapse_inactive_chapters: true  # Whether to collapse the inactive chapters in the sidebar
# #collapse_inactive_sections: true  # Whether to collapse the sub-sections within a non-active section in the sidebar
# textbook_logo             : ../Graphics/HPBrain-Anime.png  # A logo to be displayed at the top of your textbook sidebar. Should be square
# #textbook_logo_link        : https://jupyterbook.org/intro.html  # A link for the logo.
# sidebar_footer_text       : 'Powered by <a href="https://jupyterbook.org">Jupyter Book</a>'
# number_toc_chapters       : true  # Whether to add numbers to chapters in your Table of Contents. If true, you can control this at the Chapter level in _data/toc.yml

# # Search settings
# search_max_words_in_content : 100  # In the search function, use at most this many words (too many words will make search slow)

# # Controlling page information
# page_titles                    : infer  # Either `None`, `infer`, or `toc`
# page_authors                   : None  # Either `None` or `infer`
# filename_title_split_character : '_'  # If inferring titles based on filename, splt on this character.

# # Math settings
# number_equations               : false  # Whether to automatically number all block equations with MathJax

# ########################
# # Interact link settings
# ########################

# # General interact settings
# use_jupyterlab                   : true  # If 'true', interact links will use JupyterLab as the interface

# # Jupyterhub link settings
# use_jupyterhub_button            : false  # If 'true', display a button that will direct users to a JupyterHub (that you provide)
# jupyterhub_url                   : ""  # The URL for your JupyterHub. If no URL, use ""
# jupyterhub_interact_text         : "Interact"  # The text that interact buttons will contain.

# # Binder link settings
# use_binder_button                : true  # If 'true', add a binder button for interactive links
# binderhub_url                    : "https://mybinder.org"  # The URL for your BinderHub. If no URL, use ""
# binder_repo_base                 : "https://github.com/"  # The site on which the textbook repository is hosted
# binder_repo_org                  : "LarsonLab"  # The username or organization that owns this repository
# binder_repo_name                 : "MRI-education-resources"  # The name of the repository on the web
# binder_repo_branch               : "master"  # The branch on which your textbook is hosted.
# binderhub_interact_text          : "Launch Binder"  # The text that interact buttons will contain.

# # Thebelab settings
# use_thebelab_button              : true  # If 'true', display a button to allow in-page running code cells with Thebelab
# thebelab_button_text             : "Interact Inline"  # The text to display inside the Thebelab initialization button
# codemirror_theme                 : "abcdef"  # Theme for codemirror cells, for options see https://codemirror.net/doc/manual.html#config

# # nbinteract settings
# use_show_widgets_button              : true  # If 'true', display a button to allow in-page running code cells with nbinteract

# # Download settings
# use_download_button              : true  # If 'true', display a button to download a zip file for the notebook
# download_button_text             : "Download" # The text that download buttons will contain
# download_page_header             : "Made with Jupyter Book" # A header that will be displayed at the top of and PDF-printed page


# #######################################################################################
# # Jupyter book extensions and additional features

# # Bibliography and citation settings. See https://github.com/inukshuk/jekyll-scholar#configuration for options
# scholar:
#   style: apa


# # Add a bibtex file so that we can create citations?
# #bibtex_bibfiles:
# #  - references.bib


# #######################################################################################
# # Jupyter book settings you probably don't need to change

# content_folder_name       : "content"  # The folder where your raw content (notebooks/markdown files) are located
# images_url                : "/assets/images" # Path to static image files
# css_url                   : "/assets/css" # Path to static CSS files
# js_url                    : "/assets/js" # Path to JS files
# custom_static_url         : "/assets/custom" # Path to user's custom CSS/JS files

# #######################################################################################
# # Jekyll build settings (only modify if you know what you're doing)

# # Site settings
# defaults:
#   - scope:
#       path: ""
#     values:
#       layout: "default"
#       toc: true
#       toc_label: "  On this page"
#       toc_icon: "list-ul"
#       excerpt: ''

# favicon_path: "images/logo/favicon.ico"

# # Markdown Processing
# markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

# sass:
#   style: compressed

# collections:
#   build:
#     output: true
#     permalink: /:path.html

# # Exclude from processing.
# # The following items will not be processed, by default. Create a custom list
# # to override the default setting.
# exclude:
#   - scripts/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# plugins:
#   - jekyll-redirect-from
#   - jekyll-scholar
